# Generated by Django 4.0.6 on 2022-10-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_categories_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_name',
            field=models.CharField(choices=[('mobiles', 'mobiles'), ('earphones', 'earphones'), ('watches', 'watches')], max_length=50, unique=True),
        ),
    ]
