# Generated by Django 4.0.6 on 2022-10-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0006_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.CharField(max_length=120)),
            ],
        ),
    ]
